package com.pennonedu.student_sign_api.entity;

import java.io.Serializable;

public class FlowFileAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.flow_id
     *
     * @mbg.generated
     */
    private Integer flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.file_id
     *
     * @mbg.generated
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.seal_path
     *
     * @mbg.generated
     */
    private String sealPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.seal_position
     *
     * @mbg.generated
     */
    private String sealPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.created_at
     *
     * @mbg.generated
     */
    private Integer createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.updated_at
     *
     * @mbg.generated
     */
    private Integer updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.seal_page
     *
     * @mbg.generated
     */
    private Byte sealPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.seal_width
     *
     * @mbg.generated
     */
    private Short sealWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.seal_height
     *
     * @mbg.generated
     */
    private Short sealHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.seal_llx
     *
     * @mbg.generated
     */
    private Float sealLlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.seal_lly
     *
     * @mbg.generated
     */
    private Float sealLly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.seal_urx
     *
     * @mbg.generated
     */
    private Float sealUrx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file_account.seal_ury
     *
     * @mbg.generated
     */
    private Float sealUry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.id
     *
     * @return the value of flow_file_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.id
     *
     * @param id the value for flow_file_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.flow_id
     *
     * @return the value of flow_file_account.flow_id
     *
     * @mbg.generated
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withFlowId(Integer flowId) {
        this.setFlowId(flowId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.flow_id
     *
     * @param flowId the value for flow_file_account.flow_id
     *
     * @mbg.generated
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.file_id
     *
     * @return the value of flow_file_account.file_id
     *
     * @mbg.generated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withFileId(Integer fileId) {
        this.setFileId(fileId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.file_id
     *
     * @param fileId the value for flow_file_account.file_id
     *
     * @mbg.generated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.account_id
     *
     * @return the value of flow_file_account.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withAccountId(Integer accountId) {
        this.setAccountId(accountId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.account_id
     *
     * @param accountId the value for flow_file_account.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.seal_path
     *
     * @return the value of flow_file_account.seal_path
     *
     * @mbg.generated
     */
    public String getSealPath() {
        return sealPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withSealPath(String sealPath) {
        this.setSealPath(sealPath);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.seal_path
     *
     * @param sealPath the value for flow_file_account.seal_path
     *
     * @mbg.generated
     */
    public void setSealPath(String sealPath) {
        this.sealPath = sealPath == null ? null : sealPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.seal_position
     *
     * @return the value of flow_file_account.seal_position
     *
     * @mbg.generated
     */
    public String getSealPosition() {
        return sealPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withSealPosition(String sealPosition) {
        this.setSealPosition(sealPosition);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.seal_position
     *
     * @param sealPosition the value for flow_file_account.seal_position
     *
     * @mbg.generated
     */
    public void setSealPosition(String sealPosition) {
        this.sealPosition = sealPosition == null ? null : sealPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.created_at
     *
     * @return the value of flow_file_account.created_at
     *
     * @mbg.generated
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withCreatedAt(Integer createdAt) {
        this.setCreatedAt(createdAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.created_at
     *
     * @param createdAt the value for flow_file_account.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.updated_at
     *
     * @return the value of flow_file_account.updated_at
     *
     * @mbg.generated
     */
    public Integer getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withUpdatedAt(Integer updatedAt) {
        this.setUpdatedAt(updatedAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.updated_at
     *
     * @param updatedAt the value for flow_file_account.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Integer updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.seal_page
     *
     * @return the value of flow_file_account.seal_page
     *
     * @mbg.generated
     */
    public Byte getSealPage() {
        return sealPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withSealPage(Byte sealPage) {
        this.setSealPage(sealPage);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.seal_page
     *
     * @param sealPage the value for flow_file_account.seal_page
     *
     * @mbg.generated
     */
    public void setSealPage(Byte sealPage) {
        this.sealPage = sealPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.seal_width
     *
     * @return the value of flow_file_account.seal_width
     *
     * @mbg.generated
     */
    public Short getSealWidth() {
        return sealWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withSealWidth(Short sealWidth) {
        this.setSealWidth(sealWidth);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.seal_width
     *
     * @param sealWidth the value for flow_file_account.seal_width
     *
     * @mbg.generated
     */
    public void setSealWidth(Short sealWidth) {
        this.sealWidth = sealWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.seal_height
     *
     * @return the value of flow_file_account.seal_height
     *
     * @mbg.generated
     */
    public Short getSealHeight() {
        return sealHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withSealHeight(Short sealHeight) {
        this.setSealHeight(sealHeight);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.seal_height
     *
     * @param sealHeight the value for flow_file_account.seal_height
     *
     * @mbg.generated
     */
    public void setSealHeight(Short sealHeight) {
        this.sealHeight = sealHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.seal_llx
     *
     * @return the value of flow_file_account.seal_llx
     *
     * @mbg.generated
     */
    public Float getSealLlx() {
        return sealLlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withSealLlx(Float sealLlx) {
        this.setSealLlx(sealLlx);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.seal_llx
     *
     * @param sealLlx the value for flow_file_account.seal_llx
     *
     * @mbg.generated
     */
    public void setSealLlx(Float sealLlx) {
        this.sealLlx = sealLlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.seal_lly
     *
     * @return the value of flow_file_account.seal_lly
     *
     * @mbg.generated
     */
    public Float getSealLly() {
        return sealLly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withSealLly(Float sealLly) {
        this.setSealLly(sealLly);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.seal_lly
     *
     * @param sealLly the value for flow_file_account.seal_lly
     *
     * @mbg.generated
     */
    public void setSealLly(Float sealLly) {
        this.sealLly = sealLly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.seal_urx
     *
     * @return the value of flow_file_account.seal_urx
     *
     * @mbg.generated
     */
    public Float getSealUrx() {
        return sealUrx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withSealUrx(Float sealUrx) {
        this.setSealUrx(sealUrx);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.seal_urx
     *
     * @param sealUrx the value for flow_file_account.seal_urx
     *
     * @mbg.generated
     */
    public void setSealUrx(Float sealUrx) {
        this.sealUrx = sealUrx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file_account.seal_ury
     *
     * @return the value of flow_file_account.seal_ury
     *
     * @mbg.generated
     */
    public Float getSealUry() {
        return sealUry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    public FlowFileAccount withSealUry(Float sealUry) {
        this.setSealUry(sealUry);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file_account.seal_ury
     *
     * @param sealUry the value for flow_file_account.seal_ury
     *
     * @mbg.generated
     */
    public void setSealUry(Float sealUry) {
        this.sealUry = sealUry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flowId=").append(flowId);
        sb.append(", fileId=").append(fileId);
        sb.append(", accountId=").append(accountId);
        sb.append(", sealPath=").append(sealPath);
        sb.append(", sealPosition=").append(sealPosition);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", sealPage=").append(sealPage);
        sb.append(", sealWidth=").append(sealWidth);
        sb.append(", sealHeight=").append(sealHeight);
        sb.append(", sealLlx=").append(sealLlx);
        sb.append(", sealLly=").append(sealLly);
        sb.append(", sealUrx=").append(sealUrx);
        sb.append(", sealUry=").append(sealUry);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}