package com.pennonedu.student_sign_api.entity;

import java.io.Serializable;

public class FlowAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_account.flow_id
     *
     * @mbg.generated
     */
    private Integer flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_account.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_account.account_name
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_account.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_account.created_at
     *
     * @mbg.generated
     */
    private Integer createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_account.updated_at
     *
     * @mbg.generated
     */
    private Integer updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_account.id
     *
     * @return the value of flow_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    public FlowAccount withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_account.id
     *
     * @param id the value for flow_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_account.flow_id
     *
     * @return the value of flow_account.flow_id
     *
     * @mbg.generated
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    public FlowAccount withFlowId(Integer flowId) {
        this.setFlowId(flowId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_account.flow_id
     *
     * @param flowId the value for flow_account.flow_id
     *
     * @mbg.generated
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_account.account_id
     *
     * @return the value of flow_account.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    public FlowAccount withAccountId(Integer accountId) {
        this.setAccountId(accountId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_account.account_id
     *
     * @param accountId the value for flow_account.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_account.account_name
     *
     * @return the value of flow_account.account_name
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    public FlowAccount withAccountName(String accountName) {
        this.setAccountName(accountName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_account.account_name
     *
     * @param accountName the value for flow_account.account_name
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_account.status
     *
     * @return the value of flow_account.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    public FlowAccount withStatus(Byte status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_account.status
     *
     * @param status the value for flow_account.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_account.created_at
     *
     * @return the value of flow_account.created_at
     *
     * @mbg.generated
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    public FlowAccount withCreatedAt(Integer createdAt) {
        this.setCreatedAt(createdAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_account.created_at
     *
     * @param createdAt the value for flow_account.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_account.updated_at
     *
     * @return the value of flow_account.updated_at
     *
     * @mbg.generated
     */
    public Integer getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    public FlowAccount withUpdatedAt(Integer updatedAt) {
        this.setUpdatedAt(updatedAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_account.updated_at
     *
     * @param updatedAt the value for flow_account.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Integer updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flowId=").append(flowId);
        sb.append(", accountId=").append(accountId);
        sb.append(", accountName=").append(accountName);
        sb.append(", status=").append(status);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}