package com.pennonedu.student_sign_api.entity;

import java.io.Serializable;

public class FlowFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file.flow_id
     *
     * @mbg.generated
     */
    private Integer flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file.created_at
     *
     * @mbg.generated
     */
    private Integer createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_file.updated_at
     *
     * @mbg.generated
     */
    private Integer updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file.id
     *
     * @return the value of flow_file.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file
     *
     * @mbg.generated
     */
    public FlowFile withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file.id
     *
     * @param id the value for flow_file.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file.flow_id
     *
     * @return the value of flow_file.flow_id
     *
     * @mbg.generated
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file
     *
     * @mbg.generated
     */
    public FlowFile withFlowId(Integer flowId) {
        this.setFlowId(flowId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file.flow_id
     *
     * @param flowId the value for flow_file.flow_id
     *
     * @mbg.generated
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file.name
     *
     * @return the value of flow_file.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file
     *
     * @mbg.generated
     */
    public FlowFile withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file.name
     *
     * @param name the value for flow_file.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file.path
     *
     * @return the value of flow_file.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file
     *
     * @mbg.generated
     */
    public FlowFile withPath(String path) {
        this.setPath(path);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file.path
     *
     * @param path the value for flow_file.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file.created_at
     *
     * @return the value of flow_file.created_at
     *
     * @mbg.generated
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file
     *
     * @mbg.generated
     */
    public FlowFile withCreatedAt(Integer createdAt) {
        this.setCreatedAt(createdAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file.created_at
     *
     * @param createdAt the value for flow_file.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_file.updated_at
     *
     * @return the value of flow_file.updated_at
     *
     * @mbg.generated
     */
    public Integer getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file
     *
     * @mbg.generated
     */
    public FlowFile withUpdatedAt(Integer updatedAt) {
        this.setUpdatedAt(updatedAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_file.updated_at
     *
     * @param updatedAt the value for flow_file.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Integer updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flowId=").append(flowId);
        sb.append(", name=").append(name);
        sb.append(", path=").append(path);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}