package com.pennonedu.student_sign_api.dao;

import com.pennonedu.student_sign_api.entity.AccountCert;
import com.pennonedu.student_sign_api.entity.AccountCertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface AccountCertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    long countByExample(AccountCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    int deleteByExample(AccountCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    int insert(AccountCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    int insertSelective(AccountCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    List<AccountCert> selectByExampleWithRowbounds(AccountCertExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    List<AccountCert> selectByExample(AccountCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    AccountCert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AccountCert record, @Param("example") AccountCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AccountCert record, @Param("example") AccountCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccountCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_cert
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccountCert record);
}