package com.pennonedu.student_sign_api.dao;

import com.pennonedu.student_sign_api.entity.FlowAccount;
import com.pennonedu.student_sign_api.entity.FlowAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface FlowAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    long countByExample(FlowAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    int deleteByExample(FlowAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    int insert(FlowAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    int insertSelective(FlowAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    List<FlowAccount> selectByExampleWithRowbounds(FlowAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    List<FlowAccount> selectByExample(FlowAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    FlowAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowAccount record, @Param("example") FlowAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowAccount record, @Param("example") FlowAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowAccount record);
}