package com.pennonedu.student_sign_api.dao;

import com.pennonedu.student_sign_api.entity.FlowFileAccount;
import com.pennonedu.student_sign_api.entity.FlowFileAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface FlowFileAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    long countByExample(FlowFileAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    int deleteByExample(FlowFileAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    int insert(FlowFileAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    int insertSelective(FlowFileAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    List<FlowFileAccount> selectByExampleWithRowbounds(FlowFileAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    List<FlowFileAccount> selectByExample(FlowFileAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    FlowFileAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowFileAccount record, @Param("example") FlowFileAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowFileAccount record, @Param("example") FlowFileAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowFileAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_file_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowFileAccount record);
}